# Generated by Django 6.0.7 on 2026-08-03 13:44

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('morning', 'Morning briefing'), ('deadline', 'Deadline reminder'), ('productivity', 'Low productivity'), ('inactive_repo', 'Inactive repository'), ('project_delay', 'Project delay'), ('learning', 'Learning reminder'), ('github', 'GitHub reminder'), ('deployment', 'Deployment reminder'), ('info', 'Info')], db_index=True, max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=16)),
                ('link', models.CharField(blank=True, max_length=300)),
                ('read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'read'], name='notificatio_owner_i_568676_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_type', models.CharField(choices=[('deadline_reminder', 'Deadline reminder'), ('inactive_repo', 'Inactive repository'), ('low_productivity', 'Low productivity'), ('project_delay', 'Project delay'), ('github_streak', 'GitHub streak')], db_index=True, max_length=32)),
                ('enabled', models.BooleanField(default=True)),
                ('threshold', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner', 'rule_type'), name='unique_notification_rule')],
            },
        ),
    ]
