import { Badge } from "@/components/ui/badge";
import type { StatusTone } from "@/lib/status";

/**
 * Provenance badge — what actually produced this content.
 *
 * REAL_AI_PROVIDER | MOCK_PROVIDER | DETERMINISTIC_TEMPLATE. Template and
 * mock output are never presented as real AI output.
 */
const PROVENANCE: Record<string, { label: string; variant: "success" | "info" | "default"; title: string }> = {
  REAL_AI_PROVIDER: {
    label: "AI provider",
    variant: "success",
    title: "Generated by a real, configured AI provider",
  },
  MOCK_PROVIDER: {
    label: "Mock provider",
    variant: "info",
    title: "Generated by the deterministic offline mock provider — not an external AI model",
  },
  DETERMINISTIC_TEMPLATE: {
    label: "Template",
    variant: "default",
    title: "Deterministic template built from your data — no AI model was used",
  },
};

export function ProvenanceBadge({ provenance }: { provenance?: string | null }) {
  if (!provenance) return null;
  const entry = PROVENANCE[provenance.toUpperCase()] ?? {
    label: provenance,
    variant: "default" as const,
    title: `Provenance: ${provenance}`,
  };
  return (
    <Badge variant={entry.variant} title={entry.title}>
      {entry.label}
    </Badge>
  );
}

/** Re-export for callers that only need the tone mapping. */
export type { StatusTone };
