# Generated by Django 6.0.7 on 2026-08-03 13:44

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('full_name', models.CharField(max_length=320)),
                ('description', models.TextField(blank=True)),
                ('language', models.CharField(blank=True, max_length=64)),
                ('url', models.URLField(blank=True)),
                ('default_branch', models.CharField(default='main', max_length=64)),
                ('stars', models.PositiveIntegerField(default=0)),
                ('forks', models.PositiveIntegerField(default=0)),
                ('open_issues', models.PositiveIntegerField(default=0)),
                ('open_prs', models.PositiveIntegerField(default=0)),
                ('last_commit_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('at_risk', 'At risk'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=16)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_commit_at'],
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField(blank=True)),
                ('published_at', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to=settings.AUTH_USER_MODEL)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='github.repository')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=300)),
                ('state', models.CharField(db_index=True, max_length=16)),
                ('author', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('additions', models.IntegerField(default=0)),
                ('deletions', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to=settings.AUTH_USER_MODEL)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='github.repository')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=300)),
                ('state', models.CharField(db_index=True, max_length=16)),
                ('labels', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to=settings.AUTH_USER_MODEL)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='github.repository')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GithubInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(default='recommendation', max_length=32)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=16)),
                ('text', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_insights', to=settings.AUTH_USER_MODEL)),
                ('repository', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='github.repository')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sha', models.CharField(max_length=40)),
                ('author', models.CharField(max_length=120)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(db_index=True)),
                ('additions', models.IntegerField(default=0)),
                ('deletions', models.IntegerField(default=0)),
                ('changed_files', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to=settings.AUTH_USER_MODEL)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='github.repository')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('is_default', models.BooleanField(default=False)),
                ('last_commit_at', models.DateTimeField(blank=True, null=True)),
                ('commit_count', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to=settings.AUTH_USER_MODEL)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='github.repository')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('commits', models.PositiveIntegerField(default=0)),
                ('additions', models.PositiveIntegerField(default=0)),
                ('deletions', models.PositiveIntegerField(default=0)),
                ('prs_merged', models.PositiveIntegerField(default=0)),
                ('issues_closed', models.PositiveIntegerField(default=0)),
                ('active_repos', models.PositiveIntegerField(default=0)),
                ('productivity_score', models.FloatField(default=0.0)),
                ('coding_hours', models.FloatField(default=0.0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('owner', 'date'), name='unique_daily_metric')],
            },
        ),
        migrations.AddConstraint(
            model_name='repository',
            constraint=models.UniqueConstraint(fields=('owner', 'full_name'), name='unique_repo'),
        ),
        migrations.AddIndex(
            model_name='commit',
            index=models.Index(fields=['owner', 'date'], name='github_comm_owner_i_982ef8_idx'),
        ),
    ]
