# Generated by Django 6.0.7 on 2026-09-30 06:39

from django.db import migrations, models

import core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationconnection',
            name='error_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='integrationconnection',
            name='retryable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='state',
            field=models.CharField(choices=[('connected', 'Connected'), ('connecting', 'Connecting'), ('disconnected', 'Disconnected'), ('not_configured', 'Not Configured'), ('authentication_failed', 'Authentication Failed'), ('permission_denied', 'Permission Denied'), ('rate_limited', 'Rate Limited'), ('timeout', 'Timeout'), ('network_error', 'Network Error'), ('api_error', 'API Error'), ('service_unavailable', 'Service Unavailable'), ('invalid_credentials', 'Invalid Credentials'), ('stale', 'Stale'), ('no_data', 'No Data'), ('unknown_error', 'Unknown Error')], db_index=True, default='disconnected', max_length=32),
        ),
        migrations.AlterField(
            model_name='integrationconnection',
            name='access_token',
            field=core.fields.EncryptedCharField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name='integrationconnection',
            name='refresh_token',
            field=core.fields.EncryptedCharField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name='integrationconnection',
            name='status',
            field=models.CharField(choices=[('connected', 'Connected'), ('connecting', 'Connecting'), ('disconnected', 'Disconnected'), ('not_configured', 'Not Configured'), ('authentication_failed', 'Authentication Failed'), ('permission_denied', 'Permission Denied'), ('rate_limited', 'Rate Limited'), ('timeout', 'Timeout'), ('network_error', 'Network Error'), ('api_error', 'API Error'), ('service_unavailable', 'Service Unavailable'), ('invalid_credentials', 'Invalid Credentials'), ('stale', 'Stale'), ('no_data', 'No Data'), ('unknown_error', 'Unknown Error')], db_index=True, default='disconnected', max_length=32),
        ),
    ]
