# Generated by Django 6.0.7 on 2026-09-30 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0002_integrationconnection_error_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='dedup_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='alert',
            name='last_fired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='occurrences',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='insight',
            name='ai_interpretation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='insight',
            name='category',
            field=models.CharField(choices=[('development', 'Development'), ('portfolio', 'Portfolio'), ('professional_presence', 'Professional Presence'), ('project_health', 'Project Health'), ('productivity', 'Productivity'), ('goal', 'Goal'), ('system', 'System')], db_index=True, default='development', max_length=32),
        ),
        migrations.AddField(
            model_name='insight',
            name='dedup_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='insight',
            name='interpretation_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='insight',
            name='last_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insight',
            name='observed_metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='insight',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=16),
        ),
        migrations.AddField(
            model_name='insight',
            name='priority_reasoning',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='insight',
            name='provenance',
            field=models.CharField(blank=True, choices=[('REAL_CONNECTED_DATA', 'Real Connected Data'), ('USER_PROVIDED_DATA', 'User-Provided Data'), ('USER_ENTERED_MANUAL_DATA', 'User-Entered Manual Data'), ('AI_DERIVED_ANALYSIS', 'AI-Derived Analysis'), ('AI_RECOMMENDATION', 'AI Recommendation'), ('DETERMINISTIC_ANALYSIS', 'Deterministic Analysis'), ('MOCK_DATA', 'Mock Data'), ('STALE_DATA', 'Stale Data'), ('UNAVAILABLE_DATA', 'Unavailable Data'), ('ERROR', 'Error'), ('INSUFFICIENT_EVIDENCE', 'Insufficient Evidence')], db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='insight',
            name='snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insights', to='intelligence.datasnapshot'),
        ),
        migrations.AddField(
            model_name='insight',
            name='source_type',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='insight',
            name='structured_evidence',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='insight',
            name='summary',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='report',
            name='insufficient_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='provenance',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='insight',
            name='confidence',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('insufficient', 'Insufficient Evidence')], default='medium', max_length=16),
        ),
        migrations.AlterField(
            model_name='insight',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('accepted', 'Accepted'), ('dismissed', 'Dismissed'), ('converted_to_task', 'Converted to Task'), ('completed', 'Completed'), ('expired', 'Expired')], db_index=True, default='new', max_length=32),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['owner', 'dedup_key'], name='intelligenc_owner_i_335d8b_idx'),
        ),
        migrations.AddIndex(
            model_name='insight',
            index=models.Index(fields=['owner', 'dedup_key'], name='intelligenc_owner_i_2f5da2_idx'),
        ),
    ]
