# Generated by Django 6.0.7 on 2026-09-30 09:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0003_alert_dedup_key_alert_last_fired_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='insight',
            constraint=models.UniqueConstraint(condition=models.Q(('dedup_key', ''), _negated=True), fields=('owner', 'dedup_key'), name='unique_owner_insight_dedup'),
        ),
    ]
