"""Deterministic mock LLM provider.

The platform runs fully offline with this provider. Output is data-driven
rather than randomly generated: it parses the prompt for structured context
(bullet lines and `key: value` pairs) and produces a digest — so agent output
still reflects real, computed data. Real providers are drop-in replacements.
"""
import hashlib
import math
import re

from django.conf import settings

from .base import LLMProvider

_BULLET = re.compile(r"^\s*[-*]\s+(.+)$")
_KV = re.compile(r"^\s*([A-Za-z_][A-Za-z0-9 _]*?)\s*[:=]\s*(.+)$")


class MockProvider(LLMProvider):
    name = "mock"

    # ── Embeddings ─────────────────────────────────────────────────────────
    def embed(self, text: str) -> list[float]:
        dim = settings.AI_EMBEDDING_DIM
        digest = hashlib.sha256(text.encode("utf-8")).digest()
        # Expand the digest to `dim` values in [-1, 1] deterministically.
        expanded = b"".join(digest for _ in range(math.ceil(dim / len(digest))))[:dim]
        vector = [(b / 255.0) * 2.0 - 1.0 for b in expanded]
        norm = math.sqrt(sum(v * v for v in vector)) or 1.0
        return [v / norm for v in vector]

    # ── Completion ─────────────────────────────────────────────────────────
    def complete(
        self,
        system: str,
        user: str,
        *,
        temperature: float = 0.7,
        max_tokens: int | None = None,
    ) -> str:
        return self._respond(system, user)

    def chat(
        self,
        messages: list[dict],
        *,
        temperature: float = 0.7,
        max_tokens: int | None = None,
    ) -> str:
        system = next((m["content"] for m in messages if m.get("role") == "system"), "")
        user = next((m["content"] for m in reversed(messages) if m.get("role") == "user"), "")
        return self._respond(system, user)

    # ── Helpers ────────────────────────────────────────────────────────────
    def _respond(self, system: str, user: str) -> str:
        wants_json = "json" in system.lower() or user.lstrip().startswith("JSON:")
        # If the caller already handed us a formatted markdown document (headings
        # present), pass it through intact — the agents build high-quality
        # templated output, and flattening it would degrade the result.
        if not wants_json and any(line.lstrip().startswith(("# ", "## ")) for line in user.splitlines()):
            return user.rstrip()
        lines = [ln.strip() for ln in (user.removeprefix("JSON:").splitlines()) if ln.strip()]

        bullets = []
        kv: dict[str, str] = {}
        for ln in lines:
            m = _KV.match(ln)
            if m and not m.group(2).startswith("#"):
                kv[m.group(1).strip().lower()] = m.group(2).strip()
                continue
            m = _BULLET.match(ln)
            if m:
                bullets.append(m.group(1).strip())

        if wants_json:
            return self._to_json(kv, bullets)

        parts = []
        if kv:
            parts.append("**Summary of the data I received:**")
            parts.extend(f"- {k}: {v}" for k, v in kv.items())
        if bullets:
            parts.append("")
            parts.append("**Key points:**")
            parts.extend(f"- {b}" for b in bullets[:12])
        if not parts:
            parts = ["I processed your request using the mock provider. "
                     "Enable Ollama/OpenAI/Gemini in `.env` (AI_PROVIDER) for generated prose."]
        parts.append("")
        parts.append("_Generated by the local mock provider._")
        return "\n".join(parts)

    @staticmethod
    def _to_json(kv: dict, bullets: list[str]) -> str:
        obj = dict(kv)
        if bullets and not obj:
            obj = {"items": bullets[:8]}
        if not obj:
            obj = {"note": "No structured data was provided."}
        import json

        return json.dumps(obj, indent=2)
