# Generated by Django 6.0.7 on 2026-09-27 07:17

import core.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderDefinition',
            fields=[
                ('id', models.SlugField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=128)),
                ('category', models.CharField(choices=[('cloud', 'Cloud'), ('local', 'Local'), ('custom', 'Custom')], default='cloud', max_length=32)),
                ('protocol', models.CharField(choices=[('openai_chat', 'OpenAI Chat'), ('openai_responses', 'OpenAI Responses'), ('anthropic', 'Anthropic'), ('gemini', 'Gemini'), ('ollama', 'Ollama'), ('custom', 'Custom')], default='openai_chat', max_length=64)),
                ('requires_api_key', models.BooleanField(default=True)),
                ('supports_model_discovery', models.BooleanField(default=False)),
                ('supports_streaming', models.BooleanField(default=False)),
                ('supports_tools', models.BooleanField(default=False)),
                ('supports_embeddings', models.BooleanField(default=False)),
                ('default_base_url', models.URLField(blank=True)),
                ('documentation_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('base_url', models.URLField(blank=True)),
                ('model', models.CharField(blank=True, max_length=255)),
                ('api_key', core.fields.EncryptedCharField(blank=True, max_length=1024)),
                ('enabled', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=64)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('capabilities', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai.providerdefinition')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'unique_together': {('owner', 'provider')},
            },
        ),
    ]
