# Generated by Django 6.0.7 on 2026-09-27 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='providerconnection',
            unique_together=set(),
        ),
    ]
