# Generated by Django 6.0.7 on 2026-09-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_skillexecutionlog_userskillconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerconnection',
            name='last_error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='providerconnection',
            name='retryable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='providerconnection',
            name='status',
            field=models.CharField(default='disconnected', max_length=32),
        ),
    ]
