# Generated by Django 6.0.7 on 2026-08-03 13:44

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('course', 'Course'), ('docs', 'Documentation'), ('trend', 'Trend'), ('tool', 'Tool'), ('book', 'Book')], db_index=True, max_length=16)),
                ('title', models.CharField(max_length=300)),
                ('url', models.URLField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('priority', models.CharField(default='medium', max_length=16)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningRoadmap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('level', models.CharField(default='intermediate', max_length=32)),
                ('items', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_roadmaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('kind', models.CharField(choices=[('course', 'Course'), ('docs', 'Documentation'), ('trend', 'Trend'), ('tool', 'Tool'), ('book', 'Book')], default='trend', max_length=16)),
                ('title', models.CharField(max_length=300)),
                ('reason', models.TextField(blank=True)),
                ('source', models.CharField(default='agent', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'date', 'title'), name='unique_suggestion')],
            },
        ),
    ]
