"""Report generation — aggregates GitHub, productivity, and project data into
markdown/HTML reports for daily, weekly, monthly, and other periods."""
import logging
from datetime import date, timedelta

import markdown as md
from django.db.models import Sum

from ai.services import generate_prose_detailed
from ai.types import AgentResult
from core.utils import start_of_week

from .models import Report

logger = logging.getLogger("reports")

PERIOD_KEYS = ["daily", "weekly", "monthly", "quarterly", "yearly", "internship", "client"]


def period_range(period: str, today: date | None = None) -> tuple[date, date]:
    """Resolve a period label to [start, end]."""
    today = today or date.today()
    if period == "daily":
        return today, today
    if period == "weekly":
        return start_of_week(today), today
    if period == "monthly":
        return today.replace(day=1), today
    if period == "quarterly":
        quarter_month = ((today.month - 1) // 3) * 3 + 1
        return today.replace(month=quarter_month, day=1), today
    if period == "yearly":
        return today.replace(month=1, day=1), today
    if period in ("internship", "client"):
        return today - timedelta(days=29), today  # trailing 30 days
    raise ValueError(f"Unknown period: {period}")


def _github_section(owner, start: date, end: date) -> tuple[str, dict]:
    from github.models import Commit, Issue, PullRequest
    from github.services import compute_productivity_score

    commits = Commit.objects.filter(owner=owner, date__date__gte=start, date__date__lte=end).count()
    additions_agg = Commit.objects.filter(owner=owner, date__date__gte=start, date__date__lte=end).aggregate(s=Sum("additions"))
    additions = additions_agg["s"] or 0
    prs = PullRequest.objects.filter(owner=owner, state="merged", closed_at__date__gte=start, closed_at__date__lte=end).count()
    issues = Issue.objects.filter(owner=owner, state="closed", closed_at__date__gte=start, closed_at__date__lte=end).count()
    score = compute_productivity_score(owner, start, end)
    data = {"commits": commits, "additions": additions, "prs_merged": prs, "issues_closed": issues, "productivity_score": score}
    lines = [
        "## Coding",
        "",
        f"- **Commits:** {commits}",
        f"- **Lines added:** {additions:,}",
        f"- **PRs merged:** {prs}",
        f"- **Issues closed:** {issues}",
        f"- **Productivity score:** {score}/100",
    ]
    return "\n".join(lines), data


def _tasks_section(owner, start: date, end: date) -> tuple[str, dict]:
    from productivity.models import Task
    from productivity.services import productivity_score

    completed = Task.objects.filter(owner=owner, status="done", completed_at__date__gte=start, completed_at__date__lte=end).count()
    pending = Task.objects.filter(owner=owner).exclude(status__in=["done", "blocked"]).count()
    score = productivity_score(owner)
    data = {"tasks_completed": completed, "tasks_pending": pending, "productivity_score": score}
    lines = [
        "## Tasks",
        "",
        f"- **Completed:** {completed}",
        f"- **Pending:** {pending}",
        f"- **Daily productivity score:** {score}/100",
    ]
    return "\n".join(lines), data


def _projects_section(owner, start: date, end: date) -> tuple[str, dict]:
    from projects.models import Project
    from projects.services import risk_score

    projects = Project.objects.filter(owner=owner)
    rows = [{"name": p.name, "completion": p.completion_pct, "risk": risk_score(p)} for p in projects]
    lines = ["## Projects", ""]
    for row in rows:
        lines.append(f"- **{row['name']}**: {row['completion']:.0f}% complete · risk {row['risk']}/100")
    if not rows:
        lines.append("- No projects tracked.")
    return "\n".join(lines), {"projects": rows}


def _build_markdown(owner, period: str, start: date, end: date) -> tuple[str, dict]:
    title = f"{period.capitalize()} Report — {start:%b %d} to {end:%b %d}"
    sections = [
        f"# {title}",
        "",
        f"*Generated by the Report Agent on {date.today():%b %d, %Y}*",
        "",
    ]
    data: dict = {}
    for fn in (_github_section, _tasks_section, _projects_section):
        try:
            text, section_data = fn(owner, start, end)
            sections.append(text)
            data.update(section_data)
        except Exception as exc:  # pragma: no cover - one bad source shouldn't sink the report
            logger.warning("Report section failed: %s", exc)
    return "\n".join(sections), {"title": title, "period": period, "start": start.isoformat(), "end": end.isoformat(), **data}


def generate_report(owner, period: str = "daily", persist: bool = True) -> AgentResult:
    if period not in PERIOD_KEYS:
        raise ValueError(f"Unknown period: {period}")
    start, end = period_range(period)
    markdown, data = _build_markdown(owner, period, start, end)

    content, provenance = generate_prose_detailed(
        system="You are a Chief of Staff writing an executive report. Use only the supplied data, keep it concise and professional.",
        user=markdown,
        fallback=markdown,
        owner=owner,
    )
    html = md.markdown(content, extensions=["tables", "fenced_code"])

    if persist:
        report, _ = Report.objects.update_or_create(
            owner=owner,
            period=period,
            period_start=start,
            defaults={
                "title": data["title"],
                "period_end": end,
                "content": content,
                "html": html,
                "data": data,
                "generated_by": "reports-agent",
                "provenance": provenance,
            },
        )
    else:
        report = None

    return AgentResult(
        agent="reports",
        status="ok",
        summary=f"{period} report ready",
        output=content,
        data={
            "report_id": str(report.id) if report else None,
            "html": html,
            "provenance": provenance,
            **data,
        },
    )
