# Generated by Django 6.0.7 on 2026-08-03 13:44

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('internship', 'Internship'), ('client', 'Client')], db_index=True, max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('content', models.TextField()),
                ('html', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('generated_by', models.CharField(default='reports-agent', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_start', '-created_at'],
                'indexes': [models.Index(fields=['owner', 'period', 'period_start'], name='reports_rep_owner_i_6f9cd6_idx')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'period', 'period_start'), name='unique_report')],
            },
        ),
    ]
