# Generated by Django 6.0.7 on 2026-09-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='provenance',
            field=models.CharField(blank=True, default='DETERMINISTIC_TEMPLATE', max_length=32),
        ),
    ]
